### ISSUE TITLE
[BUG]: Active node not indicated in tree

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1011]
I was talking to @nielslyngsoe today and he wanted me to post an issue here to keep track of this.

At the moment the new backoffice does not indicate the active node in the tree like it used to. Here I'm clicking on a couple of nodes in the tree, content loads but the item is not marked as active.

![umb-backoffice-no-active](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/ac2398a7-1076-43c2-ac0e-24d7cf0213f7)

This used to look like this with the pink color indicating the active node in the tree.

![ns-backoffice-selection-works](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/271096da-e719-400a-a828-9220900fe884)

**Comment by enkelmedia** [comment]
@nielslyngsoe This is not "just" the indication, it's also the loading of the tree. If I reload the browser on a node "further down" in the tree - "Belle" would load children for each node in the path and indicate the current node in the tree.

Today if you open the "Blog post B"-node and reload the page (Ctrl+R) - "Articles in English" would be collapsed and the "Blog post B"-node would not be visible.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/b880d9fc-7329-45d7-9ef3-84f920ebb893)

**Comment by madsrasmussen** [comment]
Hi @enkelmedia 

The active node is now highlighted in the tree 🥳 . As mentioned in PR #1429 that's the first part. The second part is to "unfold" the menu. I will close this issue. Feel free to open one for unfolding the menu if you want to keep track of progress.
