### ISSUE TITLE
[BUG]: Actions menu behind richtext toolbar menu

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.CMS.Backoffice#1019]
**Describe the bug**
I noticed when opening Actions menu this appears behind the richtext editor toolbar menu.

**To Reproduce**
1. Go to 'All property editors' node in content section
2. Click on 'Actions' menu in upper right corner
3. Notice the actions menu is behind richtext editor toolbar menu

**Expected behavior**

**Screenshots**

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/2919859/87e46bdb-0d7f-4606-8eeb-66d0adbff441)

**Desktop (please complete the following information):**

**Additional context**

**Comment by madsrasmussen** [comment]
Thanks for reporting the issue has been fixed by PR #1138

**Comment by bjarnef** [comment]
@madsrasmussen sound great :)
I think there was something with markdown buttons as well above the tags autocomplete dropdown in the "all properties node" as well. I need to check if it  has been fixed with latest changes.
