### ISSUE TITLE
[BUG]: Release build fails with javascript error in non Chromium browsers

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco.CMS.Backoffice#1061]
I was trying to run Umbraco 14 Preview 3 but ran into an issue where I only got a blank screen. In the browser console the following javascript exception `Uncaught SyntaxError: import assertions are not currently supported icon.registry.js:1:40` was thrown. The error occours in non Chromium browsers, e.g. Firefox and Safari, because the `import ... assert {type: json}` syntax is not supported. The syntax has also been deprecated[[1]](https://caniuse.com/mdn-javascript_statements_import_import_attribues_assert_type_json) and `assert` may be replaced by the `with` keyword[[2]](https://github.com/tc39/ecma262/pull/3057)[[3]](https://tc39.es/proposal-import-attributes/), but unfortunately that is not supported[[4]](https://caniuse.com/mdn-javascript_statements_import_import_attributes_type_json) in any browsers yet.

When running `npm run dev` the error is not present, it only happens in the release build.

**Comment by iOvergaard** [comment]
Thanks, yeah we have been aware of it. We expect the major browsers to support it before release. If for some reason they don't, we have a few alternatives to consider.

**Comment by liamlaverty** [comment]
I've tested the v14-RC2 on Firefox (Windows) and Safari (Mac) this morning, and both are working. I can log into Umbraco's backoffice, and no longer receive the `Uncaught SyntaxError: import assertions are not currently supported icon.registry.js:1:40` error

**Comment by iOvergaard** [comment]
Thanks for testing, @liamlaverty. I believe this was fixed with #1656 so I'll go ahead and close this :)
