### ISSUE TITLE
Storybook for extensions

### ISSUE THREAD

**Issue by hifi-phil** [umbraco/Umbraco.CMS.Backoffice#1114]
I appreciate this is still very early days and you might have thought of this already. 

But when you release this first version will it be possible to run a storybook instance for an extension and pull in the css, design system and mocks so that an extension developer can have a component library and run interaction tests on their extension in isolation?

This will make building extensions much more robust and less likely to errors.

**Comment by enkelmedia** [comment]
@hifi-phil I'm assuming your talking about "extension" as in a package or something?

I've done that for one of my packages. Basically just follow the instructions on how to setup the development flow for the Umbraco extension and then you can run Storybook side by with with your vite-build for the extension/package. I'm basically doing something like this:

* Follow the setup-guide for extensions in the docs: https://docs.umbraco.com/umbraco-backoffice/extending/development-flow. This will build your Typescript-files into a "bundle" that will be your package.
* Install Storybook into the project: `npx storybook@latest init` https://storybook.js.org/docs/get-started/install

I've also got some inspiration from how this repository is setup to run Storybook. Not sure if I missed the point in your question but happy to elaborate if you want to ☺️

**Comment by hifi-phil** [comment]
Thanks for your reply. 

I have storybook working in the extension but it doesn't include all the backoffice styles. 

How have you done that?

**Comment by enkelmedia** [comment]
@hifi-phil I'm not exactly sure how you mean? The components in UUI have their own styling inside the components. Do you mean how to reuse this in your own components?

In that case there is the uui-css package that is used for the basic stuff: https://github.com/umbraco/Umbraco.UI/tree/v1/contrib/packages/uui-css

You could probably look at the components in this library to see how they have done to reuse basic styling, example: https://github.com/umbraco/Umbraco.UI/blob/ae00cf3a0d7be2827491b435c1a40f5d7649a504/packages/uui-button/lib/uui-button.element.ts#L234



I've added some imports to the `./storyboook/preview.ts`-file:

```typescript
import type { Preview } from "@storybook/web-components";

// Global import for UUI
import '@umbraco-cms/backoffice/external/uui';

// Import some CSS (could also be scss)
import './../storybook/global.css';

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
```
