### ISSUE TITLE
[BUG]: Password too short results in Unknown error on fresh install

### ISSUE THREAD

**Issue by jemomi-twoday-co3** [umbraco/Umbraco.CMS.Backoffice#1117]
**Describe the bug**

**To Reproduce**
1. Make a clean install using prerelease from docs: https://docs.umbraco.com/umbraco-backoffice/getting-started/installing-preview-builds
2. After filling out the installation "form", with a password shorter than 10 characters, the installation will fail, giving a blank "unknown error" message, and no information in the logs.

**Expected behavior**
If you have devtools > network active, you can see in the response from setup, that the actual error is: "Could not reset password: The password must be at least 10 characters long"

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/135309607/167a9667-981b-4ac0-8253-06e530d9c0f9)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version 120

**Comment by CarlSargunar** [comment]
working on this
