### ISSUE TITLE
Update Lit to 3

### ISSUE THREAD

**Issue by jemomi-twoday-co3** [umbraco/Umbraco.CMS.Backoffice#1118]
**Describe the solution you'd like**
Is it possible to update Lit from 2.8.0 to 3?
The latest version of `create-vite` with Lit, uses lit@3, so if possible, backoffice should probably also do this.
Docs, mention few breaking changes.

**Describe alternatives you've considered**
Alternatively we can look into creating a custom `create-vite` template that will install vite5, but with Lit2.8.
If i have time, i will potentially try running the upgrade myself.

**Additional context**
I have an issue on UmbracoDocs, about the npm script running, that is related to this: https://github.com/umbraco/UmbracoDocs/issues/5774

**Comment by iOvergaard** [comment]
Yep, we should be able to upgrade soon. Currently waiting for the UI library to support Lit 3 before we start testing it out here: https://github.com/umbraco/Umbraco.UI/pull/706
