### ISSUE TITLE
[BUG]: Right click in tree should show "action menu"

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1158]
**Describe the bug**

When right-clicking something in the tree in Bellissima we get the standard browser menu, the only way to get to the actions is via the "dots".

![bellissima-tree-right-click](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/271acb0d-18ea-411e-ab2e-9647e8cc9674)

It used to work like this which is very nice:

![before-tree-right-click](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/9a4c91a6-c060-472f-b4cc-7dc18c30f56d)

**Comment by iOvergaard** [comment]
Hasn't been implemented yet - we will get to it later on ☺️
