### ISSUE TITLE
[BUG]: OS max path limit exceeded

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco.CMS.Backoffice#1167]
**Describe the bug**
Hi I just tried installing the 14.0.0--preview004 and got the following error:
```stacktrace
System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "C:\Users\nikol\.nuget\packages\umbraco.cms.staticassets\14.0.0--preview004\staticwebassets\umbraco\backoffice\packages\core\property-editor\uis\collection-view\config\bulk-action-permissions\property-editor-ui-collection-view-bulk-action-permissions.element.d.ts". Path: C:\Users\nikol\.nuget\packages\umbraco.cms.staticassets\14.0.0--preview004\staticwebassets\umbraco\backoffice\packages\core\property-editor\uis\collection-view\config\bulk-action-permissions\property-editor-ui-collection-view-bulk-action-permissions.element.d.ts exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath)
   at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped(String currentDirectory, String evaluatedIncludeBeforeWildcardExpansionEscaped, String evaluatedIncludeEscaped, String definingProjectEscaped, String name, String& fullPath)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetBuiltInMetadataEscaped(String name)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItemCore(ITaskItem item)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromV1TaskItem(ITaskItem item)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.UpdatePackageStaticWebAssets.Execute()	MyAwesomeNightlySite	C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets	533
```

The path to this file is 262 characters so only just over the limit and when using a non-preview release the path will also be a bit shorter. It might be something to keep in mind when organizing the folders for backoffice.

**System**
- Windows 10

**To workaround this**
If you want to workaround this issue you can move the `.nuget` folder using a `nuget.config` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Umbraco Prerelease" value="https://www.myget.org/F/umbracoprereleases/api/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <add key="globalPackagesFolder" value="C:\.nuget" />
  </config>
</configuration>
```

**To Reproduce**
If you need to reproduce the issue on a system you can move the folder like so to make the path longer:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Umbraco Prerelease" value="https://www.myget.org/F/umbracoprereleases/api/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <add key="globalPackagesFolder" value="C:\Users\LongUserNameWouldBeHere\.nuget" />
  </config>
</configuration>
```

**Comment by nul800sebastiaan** [comment]
I guess some kind of fix is being added in the next beta - https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1478

**Comment by iOvergaard** [comment]
@nul800sebastiaan Yes and no. With the change in #1478 we now know which paths are problematic. We need to go through them and shorten them a bit. In reality, it isn't very many paths hitting this limit, so if someone would like to do it and then test it on their Windows machine, it would be wonderful.

The script you linked to outputs the paths on all builds running on this repository, so you can check it out on the latest build for instance: https://github.com/umbraco/Umbraco.CMS.Backoffice/actions/runs/8522951549

**Comment by gregor-tusar-sowa** [comment]
Hi,
I stumbled upon this issue while migrating from v13 to v14. 
The problematic files that I had trouble with were
- `node_modules\@umbraco-cms\backoffice\dist-cms\packages\block\block-grid\property-editors\block-grid-type-configuration\property-editor-ui-block-grid-type-configuration.element.js`.
- `node_modules\@umbraco-cms\backoffice\dist-cms\packages\documents\documents\user-permissions\input-document-granular-user-permission\input-document-granular-user-permission.element.d.ts`

So when you add drive letter, src folder and company/project name you quickly exceed the limit. 

Will this files names be obfuscated or at least shortened to a more reasonable lenght?
