### ISSUE TITLE
[BUG]: Extension of alias "my.dashboard.test" did not succeed creating an element class instance via the extension manifest property 'element', using either a 'element' or 'default' export

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco.CMS.Backoffice#1220]
**Describe the bug**
I registered a dashboard, My Dashboard Test, and it works as expected, but I get an error in the console: 
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/88326257/40a6b99a-6b0b-4a01-b8d9-3e3137a1f5df)

**To Reproduce**
umbraco-package.json:
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/88326257/25437837-10d0-450b-a202-e357a3cc7dcc)

The TS file:
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/88326257/60f1e5a1-ecb8-41c0-9c8e-6d88b6bdf366)

**Expected behavior**
The dashboard is working as expected:
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/88326257/90ca2768-8527-4b8e-bd1d-75eeb42338b3)
But I get an error in the console stating that an element class instance could not be created using 'element' or 'default' export. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: preview004

**Comment by nathanwoulfe** [comment]
Try replacing 
```ts
element: "/App_Plugins/MyDashboardTest/dashboard.ts",
```
with
```ts
js: () => import("./dashboard.js"),
```
where the import URL is a relative path to the dashboard component file.

**Comment by RasmusUmbraco** [comment]
Thank you for the suggestion, Nathan. 

I get an error with this line (it expects a value in the parenthesis): 
`js: () => import("./dashboard.js"),`
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/88326257/074ed57f-4f68-4e29-bf6d-0e5a8bbe8a62)

If I write the path on the js property like this:
`js: "/App_Plugins/MyDashboardTest/dashboard.js"),`
I get a similar error as to when it's on the element property (but the dashboard still working): 
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/88326257/9947a508-67aa-4853-be6f-5ff259750d60)

**Comment by iOvergaard** [comment]
Just noticed this as well following the "Creating a property editor" tutorial. Apparently it doesn't work to specify an `elementName` anymore. It works if you load the file through the `js` property and remember to `export default class XXX` inside the element file.

**Comment by JoJk0** [comment]
Using `export default class MyDashboard` instead of `export class MyDashboard` fixed the issue for me

**Comment by madsrasmussen** [comment]
There are two ways to export depending on what you prefer:

1. Default export as already mentioned:  

`export default MyDashboardElement`

2. If you are not a fan of default exports you can also do named exports: 

For elements:

`export { MyDashboardElement as element };

For API's:

`export { MyApiClass as api }`

If none of these work feel free to reopen the issue 👍
