### ISSUE TITLE
[BUG]: Richtext editor Mode dropdown doesn't show values

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.CMS.Backoffice#1235]
**Describe the bug**
I noticed in configuration of Richtext editor the dropdown for "Mode" property doesn't show values.
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/023a1edb2ab57a0538860e14b00de61b6b30bd51/src/packages/core/property-editor/uis/tiny-mce/manifests.ts#L212-L223

**Expected behavior**
The configured values `Classic` and `Inline` of dropdown should be shown.

**Screenshots**

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/2919859/03b2e8e7-dfe8-4449-a709-9ca9000203f3)

**Comment by leekelleher** [comment]
@bjarnef Thanks for reporting this. I believe this was fixed for 14.0.0-RC2, and UI changed to be radio-buttons.
