### ISSUE TITLE
[BUG]: No save button for block element type config

### ISSUE THREAD

**Issue by JoJk0** [umbraco/Umbraco.CMS.Backoffice#1401]
**Describe the bug**
Save button doesn't exist when Block element type config is shown (e.g. when adding new block based on element type in block grid)

**To Reproduce**
0. Create any element type
1. Create a document type with property that uses block grid, or block list
2. Open the property editor config linked to the property
3. Add new block to the block grid / list
4. Select an element type to be added
5. Observe lack of presence of the save button

**Expected behavior**
Save button to be shown so the element type can be added to block editor

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/10449993/e28e5c03-5831-4b14-be78-ef7023b04d7a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 122.0.2365.66

**Comment by nul800sebastiaan** [comment]
Thanks for the report! This has been fixed already and will be available in beta003.
