### ISSUE TITLE
[BUG]: Start Node is ignored in the Tree Picker property editor

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco.CMS.Backoffice#1456]
**Version**
14.0.0-beta001

**The issue**
Using the Tree Picker property editor, whatever is configured as start node is ignored.

**To Reproduce**
1. Define a DataType based on Umb.PropertyEditorUi.TreePicker | Umbraco.MultiNodeTreePicker
2. Click on 'Specify Root Node'
3. Select Specific Node and pick a document in the tree
4. Save the datatype
5. Use the new DataType in a document
6. When clicking the "Choose" button, the entire content tree is displayed and any node (outside the configured start node) can be selected.

**Comment by JoseMarcenaro** [comment]
Update: issue still happening in v14.0.0-beta002

**Comment by leekelleher** [comment]
@JoseMarcenaro Thank you for reporting this. 👍 

We've been working towards getting the parent/ancestor context working for the content nodes, which is what the Dynamic Root requires to calculate the start node for the Tree Picker.  We'll aim to get these parts wired up for an upcoming beta.

**Comment by madsrasmussen** [comment]
This has now been fixed and will be part of RC4
