### ISSUE TITLE
[BUG]: beta002 - Tree icon placement off 

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.CMS.Backoffice#1457]
In all of the trees the expand/collapse icons seem to be too high:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/304656/02b17ffb-b6fc-44cb-9522-8af71f8bb27b)

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/304656/3a200cb6-d970-4cc1-9232-fbeba6c29049)

And icons for, for example, creating new media items are placed too low: 

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/304656/c1c181c0-9299-488c-a75c-55ec2b807168)
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/304656/3964d7c6-9c19-44dd-a399-e58020025ba2)

**Comment by nul800sebastiaan** [comment]
The "Audio" icon looks like waves in the water by the way, surely we should have a better icon for it?

**Comment by bjarnef** [comment]
I think one of these would be better as icon for Audio media type:
https://lucide.dev/icons/audio-lines
https://lucide.dev/icons/audio-waveform

**Comment by mjpraxis** [comment]
I tried to find where in the source the css settings for the icons in the tree is sat. But have not been able to locate it yet.

Maybe some one else is lucky.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/47383499/68e5669c-4967-4dde-8786-511ccd3eb55a)

**Comment by iOvergaard** [comment]
Thank you everybody. This issue has been resolved with #1477 #h5yr

**Comment by bjarnef** [comment]
@iOvergaard perhaps any of these icons instead for Audio media type?
https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1457#issuecomment-2009446040

**Comment by iOvergaard** [comment]
@nul800sebastiaan and @bjarnef please create a new issue if you want to discuss which icons to use, thank you in advance ;-)
