### ISSUE TITLE
[BUG]: Umbraco14.0.0 beta002 Creating a mediaitem underneath a folder doesn't work

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/Umbraco.CMS.Backoffice#1460]
**Describe the bug**
When you create a folder and select 'Create' from the Context menu you get a 'The specified media type was not found error' instead of a dialog with allowed media items

**To Reproduce**
1. Create a folder in the media library
2. Navigate to that folder in  the tree
3. Select 'Create' from the context menu 
4. See the error

**Expected behavior**
A dialog with all allowed options

**Comment by enkelmedia** [comment]
Same issue for me with the content-section on Beta002:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/3e865c87-3b1e-424d-b066-ebb3fadd96eb)

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/352596b3-2f81-453d-9b90-f035d416f601)

**Comment by madsrasmussen** [comment]
Hi @rsoeteman 

Thanks for the report. Both issues have been fixed either in Beta3 or RC1.
