### ISSUE TITLE
[BUG]: Umbraco14.0.0 beta002 Navigating to the info content app  on a media item throws an error

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/Umbraco.CMS.Backoffice#1461]
When you open a media item and navigate to the info content app you get the following error 

"Incorrect syntax near the keyword 'key'. Incorrect syntax near the keyword 'key'. Incorrect syntax near the keyword 'key'. Invalid usage of the option NEXT in the FETCH statement.
A fatal server error occurred. If this continues, please reach out to your administrator."

**To Reproduce**
1. Open a media item
2. Navigate to the info content app
3. See the error

**Comment by madsrasmussen** [comment]
Hi @rsoeteman 

Thanks for the report 🏅 . I just did a test in RC1 and it looks like the issue has been fixed. Can you give it another spin? Let me know if you still see the issue.
