### ISSUE TITLE
[QUESTION/FEATURE]: What happened to keyboard shortcuts?

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1483]
**Describe the bug**
I've noticed in that I really miss the keyboard shortcuts for saving and publishing a node. Also for saving (Ctrl+S) e.g. when working with Content Type, Data Types and Dictionaries.

**Comment by iOvergaard** [comment]
This is slated for 14.3 at the moment :)
