### ISSUE TITLE
[FEATURE]: Show current Umbraco version

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1484]
**Describe the bug**
It used to be possible to see the current Umbraco version by clicking on the ?-icon in the top right corner:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/564d2633-d9f1-4c1e-984b-5353ad83c940)

It might be possible exposed somewhere in Bellissima but I can't seem to find it, maybe we should add it here:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/76fb424b-77c7-4d22-b59e-3987032498c3)

I know that this could be implemented with a extension with the new flexible extension points but I would hope that this is something that can be included out of the box.

Cheers!

**Comment by bjarnef** [comment]
It should be available clicking the Umbraco logo as well.
The Help header app may be part of Umbraco 14, but not sure it the "drawer" will be replaced by an overlay instead as I think it was only used here in the current backoffice.

**Comment by madsrasmussen** [comment]
Hi @enkelmedia 

I am happy to say that this issue has been fixed in PR #1638 and is part of RC1.
