### ISSUE TITLE
[BUG]: Icons broken in Storybook

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1486]
**Describe the bug**
The icons from the backoffice-project does not work in the backoffice storybook:

https://apidocs.umbraco.com/v14/ui/?path=/docs/umb-icons--docs

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/be12daf5-0216-4103-8a41-5bdb8aedcc05)

Also means missing icons in any component preview:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/0a67bbd0-4638-4d97-87c9-8dcc5a2e3ffb)

Now when a lot of people is starting to work on packages, it would be good for the development experience if the icons works in the storybook (they used to).

**Comment by madsrasmussen** [comment]
The seems to have been a glitch in the matrix 👨‍💻  I have just tested the current version of Storybook and the icons a back to life. Let us know if they still don't show up.
