### ISSUE TITLE
[FEATURE/ISSUE]: Resize sidebar

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1528]
In v8-13 we can resize the sidebar/tree if the nesting in the content tree is very deep, as far as I can see this is not possible in Bellissima (yet?). 

![umb-resize-sidebar](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/297c862b-eaf0-4354-ac11-5ff148f79716)

Just wanted to put this on the radar is it might be a showstopper for people that have really deep nesting.

**Comment by nathanwoulfe** [comment]
Piggy-backing on this, the sidebar no longer collapses at small screen sizes. To be fair, I don't see ultra-small screens as a priority, but wanted to mention for visibility.

**Comment by madsrasmussen** [comment]
Hi @enkelmedia 

I can happily say that this issue has been fixed as part of #1795
