### ISSUE TITLE
[BUG]: Unloading extensions from entry point feels hacky

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#1551]
**Describe the bug**
I have a package that replaces the dictionary dashboard with a custom dashboard. When I played with the API to `unregister` a certain extension it did not really work as I expected.

I did something like this:

```typescript
export const onInit: UmbEntryPointOnInit = (host, extensionRegistry) => {
    if(extensionRegistry.isRegistered("Umb.Dashboard.Dictionary.Overview")) 
    {
        extensionRegistry.unregister("Umb.Dashboard.Dictionary.Overview");
    }
};
```

I noticed a couple of things.

First, the Entry Point for my extension is always loaded before the extensions from the backoffice. No matter if I set the `weight` in `umbraco-package.json` to something crazy. No matter this use case I think it would make more sense if the core stuff is loaded before any packages, right now my custom section shows up first.

![umb-entry-point-loading](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/f1406ba4-4398-4ea6-ba09-b4b1153a8d2e)

I guess that the best things would be if we could use `weight` to control this.

Since my goal is to remove the dashboard I right now need to write some hack that pulls the registry to look for the dashboard extension and remove it as soon as it shows up. I know that the registry is very dynamic but maybe it would be possible to add something where a entry point could add a callback to be called when all the initial loadings has been done?  It actually looks like `UmbBackofficeElement` is loading the bundles (used by core) first and then entry points, maybe the last thing in this loading-chain could call some callback or something.

Or maybe that any call to "unregister" will keep the alias of the extension if it was not found and block the next call to add it, then remove it from the "block list" so that any subsequential call would add it - think out loud here.

I mean, I can always chain a couple of `setTimeout` and remove the extension but it feels like it would be nice if the core could provide a nicer API for this.

This is what I currently need to do do make it work:

```typescript
setTimeout(() => {
    if(extensionRegistry.isRegistered("Umb.Dashboard.Dictionary.Overview")) 
    {
        extensionRegistry.unregister("Umb.Dashboard.Dictionary.Overview");
    }
},2500);
```
Let me know what you think, happy yo help out if I know the preferred direction.

**Comment by enkelmedia** [comment]
@nielslyngsoe would you say that your PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1600 fixas the issue I desribe here? It feels like that?

Feel free to close this if you agree.

**Comment by iOvergaard** [comment]
Hi @enkelmedia 

Yes, the `.exclude` method added in the mentioned PR allows you to exclude something now and forever without checking if it has been registered already.

I don't know if there's still an issue with the `weight` property as you suggest, but I will close this issue due to the original issue being fixed. Feel free to open a new issue if you experience problems with the weight.
