### ISSUE TITLE
[BUG]: Allowed document types not working

### ISSUE THREAD

**Issue by sebpdev** [umbraco/Umbraco.CMS.Backoffice#1581]
**Describe the bug**
When enabling a document type to be created under another, it does not show up and throws an error (see screenshots).

**To Reproduce**
1. Create a start page document type and allow it to be created at root.
2. Create your start page at root.
3. Create a new document type and allow it to be created under the start page document type.
4. Try creating a page under the start page.
5. Get no alternatives to create, and an error message.

**Expected behavior**
My allowed document types to be available when trying to create them.

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/118893112/42130cee-829a-4285-a556-a4985c90fa65)
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/118893112/3858d2eb-7f79-4344-84e9-cbeddbc6cc40)
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/118893112/7f2a9bb5-14be-4092-9c03-5a1f0ecc6f0e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)

**Comment by iOvergaard** [comment]
Hi @sebpdev 
I tested this flow in 14.0.0-beta003 and didn't seem to be a problem anymore. Would you kindly re-test and verify?

**Comment by sebpdev** [comment]
> Hi @sebpdev I tested this flow in 14.0.0-beta003 and didn't seem to be a problem anymore. Would you kindly re-test and verify?

Sweet, I didn't think of updating but it seems to work in beta003 :)
