### ISSUE TITLE
[BUG]: v14.0.0-rc1, umbraco's login page doesn't work in Firefox

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/Umbraco.CMS.Backoffice#1640]
**Describe the bug**
The backoffice at `https://localhost:44360/umbraco` is a blank white page when accessed using Firefox. The console  contains two lines: 

```
unreachable code after return statement
[generate-umbraco-alias.function.js:6:5](https://localhost:44360/umbraco/backoffice/3da33e4bb8614452e42f6de5d8dbdd75f2af20d2/packages/core/utils/string/generate-umbraco-alias.function.js)
Uncaught SyntaxError: unexpected token: 'assert'
[icon.registry.js:1:40](https://localhost:44360/umbraco/backoffice/3da33e4bb8614452e42f6de5d8dbdd75f2af20d2/packages/core/icon-registry/icon.registry.js)
```

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/7046713/f2558a49-577d-468a-bc49-e6b241351dd5)

I'm using Firefox 124.0.2 & 125.0.1 (most recent 2 versions)

**To Reproduce**
1. Install  v14.0.0-rc1
2. Launch the site in Firefox (Windows 10)
3. User is presented with blank white page

**Expected behavior**
Login page should show up on Firefox

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 124.0.2 & 125.0.1

**Additional context**
The site works in MS Edge.

**Comment by iOvergaard** [comment]
Thanks for reporting! We are tracking this particular Firefox error, which shows up in various cases, on this issue #1061 so I'll go ahead and close this for now.
