### ISSUE TITLE
[BUG]: Published and unpublished content items share the same style in the left-hand content tree

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/Umbraco.CMS.Backoffice#1663]
**Describe the bug**

In the left-hand content tree, unpublished items are no longer greyed out in v14, and indistinguishable from published items. 

**To Reproduce**
1. In v14, Create two pieces of content, one with the _Save and publish_ action, and the other with just the _Save_ action
2. View them in the left-hand menu, both have the same dark text
3. Take the same actions in V13, in the left-hand menu, the _unpublishd_ item is greyed out to indicate that it's unpublished

**Expected behavior**
Unpublished content should have some visual differentiator in the left-hand content tree (greyed out, or with an icon of some kind).

**Screenshots**
The page titled _unpublished_ is unpublished in the tree below. It's currently indistinguishable from the other published content pieces. 

![Screenshot 2024-04-18 at 16 12 05](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/7046713/bb76cd37-8492-4273-a666-673f3a118876)

**Desktop (please complete the following information):**
- OS: macOS Sonoma 14.2.1 (23C71)
- Browser MS Edge
- Version 122.0

**Additional context**

**Comment by madsrasmussen** [comment]
Fixed by #1860
