### ISSUE TITLE
V14-RC2: The imported Element JS file did not export a `element` or `default`.

### ISSUE THREAD

**Issue by markadrake** [umbraco/Umbraco.CMS.Backoffice#1735]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14-RC2

### Bug summary

The following error is logged into the console indicative that the custom element did not load. However, the element has been rendered on the page and is working to the best of my knowledge.

`create-extension-element.function.js` line 10

```
Extension of alias "my.section" did not succeed creating an element class instance via the extension manifest property 'path/to/section.js'. 
The imported Element JS file did not export a 'element' or 'default'. 
Alternatively define the 'elementName' in the manifest.
```

I have `elementName` defined in the `umbraco-package.json`. The component is rendered on the page despite this error message indicating it couldn't be.

### Steps to reproduce

1. Create an `App_Plugins` directory.
2. Inside, create a child directory named `section`.
3. Create the following files below.

> (!!!) _I noticed you have to restart the application to pick up on these JSON settings. Is this a bug? It's less than ideal while learning to build/recycle the application to load new or updated manifests._

## Create file: `umbraco-package.json`

```
{
	"$schema": "../../../umbraco-package-schema.json",
	"name": "My.Section",
	"version": "0.1.0",
	"extensions": [
		{
			"type": "section",
			"alias": "my.section",
			"name": "My Section",
			"js": "/app_plugins/section/section.js",
			"elementName": "my-custom-section",
			"meta": {
				"label": "My Section",
				"pathname": "my-section"
			}
		}
	]
}
```

## Create file: `section.html`

```
<p>Hello!</p>
```

## Create file: `section.js`

```
class MySection extends HTMLElement {

    constructor() {
        super();
        this.initialize();
    }

    async initialize() {
        await this.loadTemplate();
    }

    async loadTemplate() {
        var template = await fetch("/app_plugins/section/section.html");
        this.attachShadow({mode: "open"});
        this.shadowRoot.innerHTML = await template.text();
    }

}

customElements.define("my-custom-section", MySection);
```

### Expected result / actual result

1. The console message should not appear. It is contradictory to what is actually happening.

**Comment by markadrake** [comment]
Hello @enkelmedia, and thanks for your response!

[So, is the `elementName` of the manifest already deprecated?](https://docs.umbraco.com/umbraco-cms/v/14.latest-rc/extending-backoffice/extension-types/property-editors/property-editor-ui#property-editor-ui). I remember reading in the documentation that you could bypass the need for a default export if you provided this optional configuration property.  

Unfortunately, I cannot find that documentation today.

→ I have found [a small reference to `elementName` here](https://github.com/umbraco/UmbracoDocs/pull/6057#issuecomment-2082906906).

The error message in the console doesn't necessarily represent an error state in the application. Without the export, the custom element still loads correctly. Perhaps it should be a warning instead? 

> I appreciate your suggestion to use TypeScript. My team has long abandoned TypeScript, and we've even removed any need for bundling. Browser support is good enough to use modules for scripts, and we can even ship nested CSS to the browser now. There's not a lot left these tools can offer us, and it's been a blessing to get rid of them both in our local environment and in our pipelines.)

**Comment by nielslyngsoe** [comment]
Hi @markadrake, good one! You are right that it worked as it should but the console error was not appropriate.

So here is a fix: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1856

Thanks

Btw. use `element` to point to your JS file instead of `js` — That is a better approch once you work with manifest types that also accepts an `api`. :-)
