### ISSUE TITLE
[ISSUE]: Not all entity types are exported

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco.CMS.Backoffice#1740]
There are a few entity types that are not exported within the package meaning that in a external package you can't define extensions for certain areas of the CMS. these include 👍 

- Dictionary
- Languages
- Media-types
- Members
- Member-Groups
- static-files ?
- partial-views
- stylesheets
- users
- user-groups
- webhooks.

I think this is a case of adding `export * './entity.js;'` in the relevant index.ts files ? 

So i  will create a PR for that

**Comment by leekelleher** [comment]
Closing, as #1741 has been merged in. Thanks @KevinJump! 🚀
