### ISSUE TITLE
[BUG]: v14rc4 - Global Search unable to tab through results

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.CMS.Backoffice#1874]
**Describe the bug**
When using the global search from the menu-bar app top right, I am unable to use my keyboard to tab through the results.

**To Reproduce**
1. Login to backoffice
2. Use `tab` key to tab to the Search in the menubar apps
3. Use `enter` key to open up the search
4. Type in a search that gives results `text`
5. Use `tab` key to tab across to Data Types and use `enter` key to select it
6. Built in datatypes related to text show up
7. Continue to use the `tab` key to try and navigate the items in the list

**Expected behavior**
When I use the tab key on the keyboard, I am able to tab through the list of search results, after tabbing past the search input field and the buttons for the filters.

**Screenshots**

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1389894/93649b23-8674-48a8-9d7d-fcaeaaa878ea)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] `Windows 10`
 - Browser [e.g. chrome, safari] `Edge`
 - Version [e.g. 22] `125.0.2535.51 (Official build) (64-bit)`

**Comment by iOvergaard** [comment]
Hi, thanks for testing this, @warrenbuckley.

So the idea is that `tab` moves through the filter and you use the `up` and `down` arrow keys to move through the results. This enables you to change the filter while you search.

I think we could make `tab` move on to the results as well, but I fear people will get annoyed that you have to tab so far to get to the results. Perhaps we could do something to indicate what shortcuts are available to you, what do you think?

**Comment by warrenbuckley** [comment]
I have no problem with using up and down arrow keys if its a common convention, but making it discoverable in the UI to know it can be done would be beneficial rather than having to guess this.
