### ISSUE TITLE
Use `uui-input-lock` in content type editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.CMS.Backoffice#1908]
**Is your feature request related to a problem? Please describe.**
I noticed template editor is using the `<uui-input-lock>` component here, but not `<umb-input-with-alias>` component like content type editor.

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/afdde10dfd74eaa1a1f415f52e4b2f448cae4c85/src/packages/templating/templates/workspace/template-workspace-editor.element.ts#L200

Any reason this can't be consistent?

Furthermore it would be great if `<umb-input-with-alias>` re-used `<uui-input-lock>` component, so it didn't need to hardcode the lock icon here:
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/afdde10dfd74eaa1a1f415f52e4b2f448cae4c85/src/packages/core/components/input-with-alias/input-with-alias.element.ts#L87-L89

**Describe the solution you'd like**
Consistency in how header with name and alias work.

**Describe alternatives you've considered**

**Additional context**

**Comment by iOvergaard** [comment]
As this has already been created on the Umbraco-CMS repository, we will continue the discussion there.
