### ISSUE TITLE
[BUG]: Dictionary Section got wrong name in header

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco.CMS.Backoffice#1986]
**Describe the bug**
The Dictionary Sections name in the header should be `Dictionary` and not `Translations`
<img width="710" alt="image" src="https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/6791648/9128433d-f2d0-4622-b1c1-6433de0a6411">

I think the wrong localization key have been set, see what is used in the headline of the sidebar.

**Comment by madsrasmussen** [comment]
Fixed by #2011
