### ISSUE TITLE
[BUG]: Unable to define a permission that can be toggled independently based on entity type

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.CMS.Backoffice#2012]
**Describe the bug**
I have the permission defined for both document and media as the entity type and toggling one, toggles the other to be enabled as well etc...

**To Reproduce**
Steps to reproduce the behaviour:
1. Use sample manifest to register new permission
2. Goto User Groups
3. Enable the permission in the Documents section
4. Notice that also the same permission in the Media entity is also enabled

```typescript
import { UMB_DOCUMENT_ENTITY_TYPE } from "@umbraco-cms/backoffice/document";
import { UMB_MEDIA_ENTITY_TYPE } from "@umbraco-cms/backoffice/media";
import { ManifestEntityUserPermission } from "@umbraco-cms/backoffice/extension-registry";

const examinePeekPermission: ManifestEntityUserPermission = {
    type: 'entityUserPermission',
    alias: 'examinepeek.permission',
    name: 'Examine Peek User Permission',
    forEntityTypes: [ UMB_DOCUMENT_ENTITY_TYPE, UMB_MEDIA_ENTITY_TYPE ],
    weight: -1000,
    meta: {
        verbs: ['ExaminePeek.Enabled'], // This is key persissted back to server & what we look up in condition
        group: 'Examine Peek',
        label: 'Enable Examine Peek',
        description: 'Allows a user to peek at the stored Examine values in the index for a given piece of content.'
    }
}
export const manifests = [examinePeekPermission];
```

**Expected behavior**
That I am able to toggle the permission that I created for the different entity types, independently from one another.

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1389894/2607fbda-063c-4b5f-b401-de34eab35a87)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 126.0.2592.56

**Additional context**
Discord thread for context
https://discord.com/channels/869656431308189746/1252600896219775058

**Comment by madsrasmussen** [comment]
Hi @warrenbuckley , 

Thanks for the bug report.

We currently persist all verbs in a string array, so the data doesn't know anything about what entity type a verb is related to. If you use the same verb across toggles they will both be "turned on" as the verb exists in the array. If you want independent permissions for each toggle you will have to make two verbs: one for documents and one for media.

I hope it makes sense.
