### ISSUE TITLE
[BUG]: media input component , removing image does not removing until page reloads 

### ISSUE THREAD

**Issue by BishalTimalsina12** [umbraco/Umbraco.CMS.Backoffice#2032]
**Describe the bug**
when i remove the image it doesnt remove it until and unless i reload the page
**To Reproduce**
1. when extending umbraco backoffice use umb-input-media component. 

**Expected behavior**
it should reflect immediate change like this input component [umb-input-upload-field]
**Screenshots**

https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/143370089/2e4d0850-4528-4378-a891-d6ca3fc9d29e

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Microsoft Edge
 - Version : 126.0.2592.68 (Official build) (64-bit)

**Comment by loivsen** [comment]
Good find! 😊
