### ISSUE TITLE
Which is the javascript language used in this new Backoffice? React?

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco.CMS.Backoffice#323]
Which is the javascript language used in this new Backoffice? React?

**Comment by iOvergaard** [comment]
Hello,

This does not look like a bug report. Please ask questions on our [forum](https://our.umbraco.com/) or [Discord server](https://discord.umbraco.com).

You can find all information regarding the [new backoffice in the RFC](https://github.com/umbraco/rfcs/blob/main/cms/0024-implement-the-new-backoffice.md).
