### ISSUE TITLE
Property Editor: Toggle - UI

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#450]
Create the UI of the property editor of 'Toggle'. Please create a story for Storybook as well.

**Comment by bkclerke** [comment]
@iOvergaard It looks like this one has been completed? There is a storybook for the toggle here: https://ambitious-stone-0033b3603.1.azurestaticapps.net/?path=/docs/components-inputs-toggle--docs. Should we move this issue to another status or is there something left to be done on this?

**Comment by iOvergaard** [comment]
No you are right, it is done, @bkclerke
