### ISSUE TITLE
Property Editor: Textbox - UI

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#452]

**Comment by bkclerke** [comment]
@iOvergaard I see the textarea is already in the backoffice. When you build the project you can see the text area on the all property editors content node. There is an odd case where you can manually expand the width of the editor past the container of the dashboard itself which is awkward (see screenshot). Is there any work left to be completed for this issue?


![Image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/4968254/940087f7-df72-45e5-b255-acba3bd98866)

**Comment by iOvergaard** [comment]
No, the UI should be good to go.
