### ISSUE TITLE
Property Editor: Textarea - UI

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#457]

**Comment by bkclerke** [comment]
@iOvergaard I see the textarea is already in the backoffice. When you build the project you can see the text area on the all property editors content node. There is an odd case where you can manually expand the width of the editor past the container of the dashboard itself which is awkward (see screenshot). Is there any work left to be completed for this issue?


![Image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/4968254/940087f7-df72-45e5-b255-acba3bd98866)

**Comment by iOvergaard** [comment]
I think it's good to go. Not really sure if we can fix that "bug", since it's browser behavior unless we turn off manual expansion. If you have a solution, feel free to create an issue here on the tracker :)
