### ISSUE TITLE
Property Actions Menu: Make it go on top

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco.CMS.Backoffice#530]
**Is your feature request related to a problem? Please describe.**
We need to solve how we make Property Actions Menu go on top of Property Editors and other things.

**Describe the solution you'd like**
Visually appear on top.

**Describe alternatives you've considered**
This can be anything, most likely something with styling or DOM structure.

**Additional context**
This image describes the current situation:
![image](https://user-images.githubusercontent.com/6791648/219900041-423fa010-5a85-4f06-a537-e75651ac298c.png)

**Comment by LouieRichardson99** [comment]
Looking into this

**Comment by nielslyngsoe** [comment]
fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/596
