### ISSUE TITLE
Eye dropper popover: Make it go on top

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco.CMS.Backoffice#598]
**Is your feature request related to a problem? Please describe.**
We need to solve how we make Eye Dropper popover go on top of Property Editors and other things.

**Describe the solution you'd like**
Visually appear on top.

**Describe alternatives you've considered**
This can be anything, most likely something with styling or DOM structure.

**Additional context**
This image describes the current situation:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/6791648/225567567-3ea409af-a41f-4d66-9bb9-340384231fd4.png">

**Comment by enkelmedia** [comment]
I figured that some of the wrapping components creates a new [Stacking Context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) which seems to be the "umb-workspace-property-layout"-component. 

![Image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/13451993-d665-4932-b134-54bccf3035c4)

When removing the "container-type: inline-size"-setting and adjust the grid-template-columns it seems like no stacking context is created:

![Image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/139d1fe5-83be-44d0-aea6-2273e3038c8c)

At the end of the day, if any wrapping element is creating a stacking context I'm not sure how a child could "escape" out of that? Feels like the CSS that I wrote here is a little hacky and there are probably edge-cases that I'm missing?

**Comment by bkclerke** [comment]
@nielslyngsoe @iOvergaard Would this overlay issue be an issue across the backoffice. It appears to affect the dropdowns in other places too. The tabs overlay on top of the actions menu and the languages dropdown is not accessible either. Is there a general style that can be updated for the overlaid options?


![Image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/4968254/360bb6cd-d85a-4f6c-ad20-b6fe3ee08632)
![Image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/4968254/c67690f1-a83f-422e-b3b4-5dda6b4f6a84)

**Comment by portfolioris** [comment]
I recommend to use the [popover API](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover) for all expanding menus. This will remove the stacking context issue.

The language menu could be a regular `<select>` element, which has all kinds of accessibility considerations implemented too.

**Comment by bjarnef** [comment]
It works it we use the new `<uui-popover-container>` (using the popover API) instead of the `<uui-popover>`, but unfortunately it is not supported in all modern browsers yet.

**Comment by enkelmedia** [comment]
The eye dropper-issues seems to be solve as of now:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/d9b2f188-0d25-4a12-92ee-11aed4d7fc69)

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/41665f79-021d-48d6-a097-9a2e4fa36333)

Maybe we should close this issue and create new unique issues for other similar cases?

**Comment by nielslyngsoe** [comment]
@enkelmedia your right, thanks!

This has been fixed by implementing the native popover api
