### ISSUE TITLE
Label property editor UI value sanitize

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#700]
The value field on the label property editor UI could contain anything such as custom HTML and scripts. We should probably test it to see if it prints out HTML correctly or if it is escaped. I know that some extensions save HTML directly in a label. We should probably also figure out if we can scrape it a bit to remove dangerous characters by running it through an HTML parser such as [sanitize-html](https://www.npmjs.com/package/sanitize-html)

_Originally posted by @iOvergaard in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/691#discussion_r1187146953_

**Comment by leekelleher** [comment]
@iOvergaard I've tested this out. If the label value contains markup, then the rendered output will be escaped.

The question is, did we want the Label property-editor to render markup?
If so, we could run it through `DOMpurify` and the `unsafeHTML` directive?

**Comment by iOvergaard** [comment]
@leekelleher we certainly have better abilities to do that now, but I'm not sure we should render unknown HTML in the property descriptions. If we wanted to, you are right in that we should run it through DOMPurify, but it begs the question: do we want to allow HTML there?

**Comment by leekelleher** [comment]
At the moment, I think we should not render any markup for the Label.
If a well argued case comes up in future, then we could consider it for a future feature.
