### ISSUE TITLE
Make notifications great again

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#840]
I think that project Bellissima is a great opportunity to innovate on the UX for notifications and how they are used. In the current versions (basically, since Belle was introduced) the notifications have been a major cause of distraction when working in the backoffice. A major problem today (in Belle) is that notifications sometimes show up on top of important action buttons like "Save and Publish" etc. and also that they tend to stick around for a very long time.

In the current version (preview-002) of Bellisima I think that notifications have gone in the wrong direction, I think that:

* The design is to "bold" for a confirmation notification
* They are potentially overused
* They stick for far too long

Here is an example:

![notifications-sticky](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/a6daf0db-fc9e-44fa-8fc9-461b029dea49)

I think that there is a lot of room for improvement for the notifications:

* Can we make "positive/success" notifications less intrusive? 
* Maybe move them to another part of the screen or "rethink" how they are shown. Maybe they could overlay the "keyboard shortcut"-area?
* Make them smaller
* Never show more than one notification at the same time but have some kind of "hidden" history if needed.
* Make them disappear immediately when on certain actions? E.g. switching section, switching tree node etc.
* Be smart about time? Maybe have an algorithm that will automatically set the timeout based on the length of the message? (and option to override if needed)

I also think that many success notifications are redundant, for example in this interaction:

![notifications-redundant](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/43931c27-5659-4275-9f73-d02c1862502e)

Here the button already indicates the success by showing the check, if this is not clear enough maybe the button behavior could be improved to make the success clearer to avoid having to show the notification.

**Comment by nielslyngsoe** [comment]
Hi @enkelmedia, I agree with your statements and I can also share that we several times internally have talked about ideas for other solutions. We do have a set scope for New Backoffice, which is that we will not be making much new features for the first version, unless they are really low hanging. Meaning that this is out of scope for now. But keep the focus on these types of details in the future and if you come up with a nice solution that you think fits well for Backoffice let us know. I'm not sure where but you can always DM me. Thanks again, I love these inputs, but sadly it's out of scope for now.

**Comment by nielslyngsoe** [comment]
Oh, I see I was maybe a bit too fast on closing the issue without replying on the specifics.

We can ofcourse adjusts on a few things here, let me apply to each of the points made by Markus:

** Make them smaller**
I guess we could, but I wouldn't see that as the real solution to the problem you experience.

**Never show more than one notification at the same time but have some kind of "hidden" history if needed.**
Yes, we already talked about this a few times, that we need to be able to control the notifications better. Currently they originate from the actual communication with the server, but they should be controlled by the UI that initiated this. ( but again this would sort of be new feature of Backoffice, so maybe will be postpone til after launch)

**Make them disappear immediately when on certain actions? E.g. switching section, switching tree node etc.**
Good idea, feel free to make a suggestion on this. I'm not sure it counts for all scenarios but generally when the user navigates it makes sense that we get rid of this. So feel free to explore a solution on that.

**Be smart about time? Maybe have an algorithm that will automatically set the timeout based on the length of the message? (and option to override if needed)**
Good idea, this component is part of UI Library, so such a feature would have to go there. But feel free to make a suggestion on such :-)
