### ISSUE TITLE
A "Clean" view for custom section without entity

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#841]
I'm looking at how to migrate packages with custom sections to the new backoffice UI. There used to be a way to include "dashboards" but without showing the tabs.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/fecffca0-c07b-4eeb-9ae5-79dd324bfe2f)

I've looked at the current documentation and when adding a dashboard there will always be a tab shown even when there is only one dashboard in the section, as here in the dictionary section:

![dashboard - dictionaries](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/5b703da6-2084-4301-a43a-05fbd4df3282)

or here in a custom section:

![dashboard for section](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/9a4f2437-b447-439d-9693-58e568c4e64a)

There should be a way to create a custom section where the whole view is available without the "header-area"?

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/3ef59151-ed1d-4d87-b7c2-498e4bf106e0)

I think that these types of extensions could benefit from this:

* sectionView - If there is only one view, don't show the tabs
* dashboard - If there is only one dashboard - don't show tabs

If we don’t want to make this the default there should at least be a setting so that one can opt-in to this behavior if needed.

**Comment by nielslyngsoe** [comment]
Hi @enkelmedia 

I agree, that is for sure.

We are currently missing some event reply from the extension slot, which should indicate the amount of extensions it holds.. and it should be an event as this can change runtime. We would need such for us to detect if we can hide the bar.

I hope that makes sense, thanks for mentioning it. I will keep the issue open as a reminder :-)

**Comment by madsrasmussen** [comment]
When you register your section you can add a custom element as part of the registration. This will give you a "clean slate", to build the section. We just have a default element we use if there is no element as part of the extension manifest. That one includes a sidebar, views, etc.

Manifest would then be something like:

`{
 type: 'section',
 alias: 'My.Section',
 elementName: 'my-section',
 js: './path/to/file.js'
 ...
}`

But it sounds like a bug that we show the dashboard tab bar if there is only one dashboard 🤔

**Comment by nielslyngsoe** [comment]
@enkelmedia that is right, you don't get scrolling unless you opt into it. Because maybe you wanted two scrolling panels or some other layout. So this is how it's done for now.

**Comment by nielslyngsoe** [comment]
@enkelmedia regarding having a Section with just one Dashboard. Then this PR fixes the rendering statement, so we don't get to see the navigation if there is only one dashboard or one section view.

So this might be what you actually wanted, instead of overwriting the section element as Mads proposed.

Doing this will enable others to bring another dashboard or view or sidebar apps to your section — I know that's a new perspective to get used to, but a cool one I think. So you can ideally extend other extensions.

**Comment by enkelmedia** [comment]
Thanks for the answers and fixes! I think that the "main issue" here is addresses and fixed now so I'll go ahead and close this one.

Cheers!
