### ISSUE TITLE
Rename section "Dictionary" to "Translation"

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#842]
In Umbraco 8-12 the section for Dictionary items has been called "Translation", personally I think that this is better but maybe there is a good reason for this change? I can see that the whole content-section also handles translations when working on a multi-lingual site. 

Just wanted to raise this, feel free to close it if you don't agree =D

**Comment by nielslyngsoe** [comment]
Hi @enkelmedia, thanks for your awareness and concern.

It is for sure a concern that some users will be used to the wording 'translations' and find it hard that the name is changed.

We found Dictionary a better match, simply cause we see that Translations can cause confusion. I'll list a few perspectives of mine:

1. As you mentioned yourself. Translations are also something that happens in Content. And this is not the place where users who come to translate things necessary should go, they maybe need to go both places.

2. It collides with extensions like the Translation Manager, https://our.umbraco.com/packages/backoffice-extensions/translation-manager/

3. Translations is a very broad term, as a package developer you are also working with translations of your UI text. 
So we are looking to avoid using the same word across these features. So it becomes easier as a newcomer to Umbraco to distinguish between the different parts. Which are 'translations of content'(Content section), and 'translations of dictionary items'(Now Dictionary section). and 'translations of UI text'(Now Localizations API).

4. Some use the Dictionary(previous Translations Section) for things that are not specifically Translations, but are more like a Multi site oriented purpose. Like API keys, social media accounts, etc. in this way they can differ these values across cultures.

I hope that gives a bit of perspective, feel free to let me know if you have other perspectives we should be aware of :-)

But until that I will close the issue for now :-)
