### ISSUE TITLE
Editors are small

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#846]
**Is your feature request related to a problem? Please describe.**
In general, when I play around in the latest preview I feel that the UX has been degraded since the latest Belle-iterations.

Here for example, the view to pick a Data Type take up very little space on the screen, even when the rest of the screen is overlayed. 

![dialogs very small](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/747eabc9-5ebf-4197-a944-e30b7a34d612)

The "Select editor"-editor could take up a lot more space like it used to do:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/a116d39c-b73e-4771-86b1-62fc9d937652)

I also think that the icons are too big in the new version of the editor.

**Comment by enkelmedia** [comment]
Following up on this one, i think that:

* The `small` option of `uui-modal-sidebar` is a little to small seems like it's 400px today, I would vote for something like 500px.
* The UMB_PROPERTY_EDITOR_UI_PICKER_MODAL` should be medium and not small.

**Comment by madsrasmussen** [comment]
Thanks for reporting. The issue has been fixed by PR #1157

**Comment by enkelmedia** [comment]
@madsrasmussen That PR fixes one of the modals but I would like so see a change to make all `small` modals a little wider.
