### ISSUE TITLE
[BUG]: Ctrl + Click should open in new window

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#883]
**Describe the bug**
Preview002

In many places in the current backoffice, it's possible to hold down ctrl (on Windows) and click to open the link in a new window, this does not work in Bellissima at the moment.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/df33bce4-6c6b-4dee-8235-89683181f537)

**Comment by sahil9001** [comment]
Can I take up this issue? @iOvergaard

**Comment by iOvergaard** [comment]
> Can I take up this issue? @iOvergaard

Sure, take a stab at it!

**Comment by sahil9001** [comment]
@iOvergaard This issue involves removing the `href` with a `@click` event, should I proceed with that approach?

**Comment by iOvergaard** [comment]
> @iOvergaard This issue involves removing the `href` with a `@click` event, should I proceed with that approach?

I would expect a href to work out of the box with ctrl+click. Perhaps we'll find the problem in the UI library?

**Comment by sahil9001** [comment]
Is it a different repository?

**Comment by nielslyngsoe** [comment]
@sahil9001 `href` should work out of the box as Jacob states. I think it could be a problem of the Tab or the Tab Group component.
It's part of https://github.com/umbraco/Umbraco.UI which is a different repo.

**Comment by nielslyngsoe** [comment]
@sahil9001 I just dived into this, and it seems to be working in the latest UI Library. So I think, notice I'm assuming here, that it is fixed in UI Library, we just need to implement the latest in New Backoffice.

**Comment by portfolioris** [comment]
This is incorrect from an accessibility perspective. The element is defined as a tab group (`role="tablist"`) with tabs (`role="tab"`). However, they are links, so they should not be identified as tabs, but as links.

My recommendation is to use a `<nav aria-labelledby="primary">` with a `ul > li > a` structure in it.

If they are links, the ctrl+click and many other issues are automatically fixed!

**Comment by sahil9001** [comment]
> @sahil9001 I just dived into this, and it seems to be working in the latest UI Library. So I think, notice I'm assuming here, that it is fixed in UI Library, we just need to implement the latest in New Backoffice.

How much effort is this? I mean do we need to change the library everywhere for this?

**Comment by iOvergaard** [comment]
Hi @sahil9001, I just made a pull request (#917) to update the UI library. Would you test to see if that fixes this problem as well, please?
