### ISSUE TITLE
[BUG]: Log Viewer saved searches do not link

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#885]
**Describe the bug**
When clicking on a saved search nothing happens.

**To Reproduce**
1. Go to settings
2. Click on Log Viewer
3. Click on any default saved search
4. The URL switches quickly back and forth and you stay the same place

**Expected behavior**
We expect to land on the "Search" view with the saved search already typed into the search field (the `?lq=` URL parameter)

**Screenshots**

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/752371/c6595ce9-89f2-4c98-b346-e8cd7155cf39)

**Comment by sahil9001** [comment]
Can I take this issue?

**Comment by iOvergaard** [comment]
> Can I take this issue?
> 
> 

Please do. Thank you so much!

**Comment by iOvergaard** [comment]
Fixed.
