### ISSUE TITLE
[BUG]: Preview development environment setup fails when installing dependencies

### ISSUE THREAD

**Issue by sophie-neale** [umbraco/Umbraco.CMS.Backoffice#897]
When setting up your development environment for the Preview Release 003 of the v14 backoffice, The installation instructions for the [Dependencies](https://docs.umbraco.com/umbraco-backoffice/extending/development-flow#dependencies) section says to install npm. This line currently throws an error requesting that we download other depencies that are not included from the myget feed.

![Error](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/35264991/49af41f9-1cc0-4276-bc1c-1ce29d8fc165)

We need to update the documentation to reflect the correct path to install the preview version but it sounds like this will need to be fixed in the code before making doc changes.

**Comment by sophie-neale** [comment]
@iOvergaard Have raised the above bug

**Comment by iOvergaard** [comment]
@sophie-neale Yes, we need to first publish the preview versions of the package on npm, because they do not work when published on myget due to transient dependencies not being present. We will have to look into this.

**Comment by iOvergaard** [comment]
@sophie-neale the documentation has now been updated through https://github.com/umbraco/UmbracoDocs/pull/5464 and the package has been published on npm. It should now work without giving trouble but do note that you have to specify the correct version number still. Please try it out :)
