### ISSUE TITLE
[BUG]: Umbraco 14 Preview 3, backoffice dashboard localization, special characters are not rendered properly

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco.CMS.Backoffice#915]
**Describe the bug**
Umbraco 14 Preview 3, backoffice dashboard localization, special characters are not rendered properly

**To Reproduce**
1. Follow guide for dashboard localization: https://docs.umbraco.com/umbraco-backoffice/tutorials/creating-a-custom-dashboard/adding-localization-to-the-dashboard
4. See special characters not rendering properly

**Expected behavior**
Expect to see special characters rendered appropriately

**Screenshots**

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/87725234/cec9c5ab-a39f-4f02-81de-436ce0d79b97)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 117

**Comment by enkelmedia** [comment]
@asawyermarathon are you sure that this is not related to encoding in your files or something? 

I'm using the Vite-build pipeline and for me Swedish characters works fine - even emojis 😊

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/a7d9e3e3-9e15-4b48-8c8d-7442ae764c51)

If you use VS Code you can check here:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/69e2d732-6576-4903-9a49-8e9f85de855a)
