### ISSUE TITLE
[BUG]: Icon colors don't change when selecting color from palette

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.CMS.Backoffice#976]
**Describe the bug**
With the new Lucide icons the icons no longer change color when selecting colors from palette in icon picker.
We should also consider e.g. yellow in color swatches as I think it would course loo low contrast.

**To Reproduce**

**Expected behavior**
Icons should change color.

**Screenshots**

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/2919859/f10e5b68-b3c1-4b04-8de7-c0b3ee7bd2ae)

**Desktop (please complete the following information):**

**Additional context**

**Comment by bjarnef** [comment]
@iOvergaard @nielslyngsoe do we really what to allow yellow and pink icon colors in new backoffice as the contrast on the white background is too low.

Maybe we should also consider a dark mode theme like the docs using GitBook. In that case I think it would be okay the overwrite icon colors in tree.

**Comment by iOvergaard** [comment]
Should be fixed in RC3.
