### ISSUE TITLE
[BUG]: Broken Storybook

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#997]
**Describe the bug**
The Storybook that is referenced in the documentation and included in the repository looks like this:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/d27d6fc9-e66f-4b22-8256-721c27ae74c7)

Does not matter where I click I get the same error.

https://apidocs.umbraco.com/v14/ui?path=/docs/guides-context-api--docs

The version of Storybook that is public here: https://apidocs.umbraco.com/v14/ui?path=/docs/guides-context-api--docs seems to be older (probably preview003) but the one in the main-branch had another issue that this PR fixes.

**Comment by iOvergaard** [comment]
This should be fixed implicitly when we release the next preview of v14, which we hope to do soon. If we find an opportunity to do so, we can probably fix it in-place. We'll see what comes first.

**Comment by enkelmedia** [comment]
It's possible to fetch down the latest main-branch locally and `npm run storybook` to get it up and running while waiting for the next preview.

I'll close this =D

**Comment by iOvergaard** [comment]
The main storybook should work now as well. We are currently in the process of preparing preview004 and Storybook has been updated as part of that: https://apidocs.umbraco.com/v14/ui/
